import tailwind from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { dirname, resolve } from "path";
import fs from "fs";
import { defineConfig } from "vite";
import dts from "vite-plugin-dts";

/**
 * Vite configuration for the Portland Design System React components package.
 *
 * This configuration sets up the build process to:
 * - Generate ES modules with CSS code splitting enabled
 * - Automatically discover and bundle all `index.ts` files in the `src` directory as library entry points
 * - Use the directory name as the entry point identifier
 * - Exclude the Lit library from the bundle (treated as external dependency)
 * - Generate output files with the pattern `${name}.${format}.js`
 * - Include React and Tailwind plugins for build processing
 *
 * @remarks
 * The entry points are dynamically generated by recursively scanning the `src` directory
 * for files named `index.ts`. Each entry point is mapped to its parent directory name.
 *
 * @example
 * For a file structure like:
 * ```
 * src/
 *   button/index.ts
 *   card/index.ts
 * ```
 * This will generate entry points: `{ button: 'src/button/index.ts', card: 'src/card/index.ts' }`
 */
export default defineConfig(({ mode }) => ({
  build: {
    cssCodeSplit: true,
    lib: {
      entry: fs
        .readdirSync(resolve(__dirname, "src"), {
          recursive: true,
          encoding: "utf-8",
        })
        .filter((file) => file.endsWith("index.ts"))
        .reduce(
          (acc, file) => {
            const name = dirname(file);
            acc[`${name}/${name}`] = resolve(__dirname, "src", file);
            return acc;
          },
          {} as Record<string, string>
        ),
      name: "ComponentsReact",
      formats: ["es"],
      fileName: (format, name) => `${name}.${format}.js`,
    },
    rollupOptions: {
      output: {
        // put emitted CSS next to JS path instead of dist/assets/*
        assetFileNames: () => "[name]/[name].[ext]",
      },
    },
    minify: mode === "production" ? "esbuild" : false, // Only minify in production
  },
  plugins: [
    dts({
      exclude: ["**/*.stories.*", "**/*.test.*"],
      rollupTypes: true,
      bundledPackages: ["@cityofportland/types"],
      entryRoot: "src",
      afterBuild: async () => {
        if (!fs.existsSync(resolve(__dirname, "dist"))) {
          return;
        }

        const files = fs
          .readdirSync(resolve(__dirname, "dist"), {
            encoding: "utf-8",
          })
          .filter((file) => file.endsWith(".d.ts"));

        for (const file of files) {
          const dir = file.split(".")[0];
          const target = resolve(__dirname, "dist", dir, `${dir}.d.ts`);
          if (file !== target)
            fs.renameSync(resolve(__dirname, "dist", file), target);
        }
      },
    }),
    react(),
    tailwind(),
  ],
}));
