on:
  pull_request:

jobs:
  test-packages-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./packages/actions/setup-build

      - run: pnpm install --frozen-lockfile

      - run: turbo build --filter=./packages/*

  test-site-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./packages/actions/setup-build

      - run: pnpm install --frozen-lockfile

      - run: turbo storybook:build --filter=./packages/*

      - run: turbo build --filter=./sites/*
