on:
  release:

jobs:
  publish-packages:
    if: ${{ github.event.action == 'published' && !github.event.release.draft }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required to use OIDC with NPM
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./packages/actions/setup-build
        with:
          package_manager_cache: false
          registry_url: "https://registry.npmjs.org/"

      - run: pnpm install --frozen-lockfile

      - run: turbo build
        working-directory: packages/actions

      - id: get-latest-run
        uses: ./packages/actions/get-latest-run
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: push.yml
          branch: main
          head_sha: ${{ github.sha }}
          conclusion: success

      - uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: dist-folders
          run-id: ${{ steps.get-latest-run.outputs.run_id }}

      - run: pnpm publish --recursive --access public --no-git-checks