on:
  release:

jobs:
  publish-packages:
    if: ${{ github.event.action == 'released' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./packages/actions/setup-build

      - run: pnpm install --frozen-lockfile

      - run: turbo build
        working-directory: packages/actions

      - id: get-latest-run
        uses: ./packages/actions/get-latest-run
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: push.yml
          head_sha: ${{ github.event.release.target_commitish }}

      - uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: dist-folders
          run-id: ${{ steps.get-latest-run.outputs.run_id }}

      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish -r --access public --no-git-checks